workflows:
  ios-build:
    name: Build iOS App for App Store
    environment:
      flutter: stable
      xcode: 15.4
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.matroodi.wholesale3
      vars:
        LC_TYPE: "en_US.UTF-8"

    scripts:
      - name: Clean old build files
        script: |
          flutter clean

      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Update CocoaPods and fix Firebase Swift issue
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS release IPA
        script: |
          flutter build ipa --release --no-tree-shake-icons --codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_KEY
        issuer_id: $APP_STORE_ISSUER_ID
        key_id: $APP_STORE_KEY_ID
        submit_to_testflight: true

      email:
        recipients:
          - hameed490@yahoo.com
        notify:
          success: true
          failure: true
