workflows:
  ios-build:
    name: Build iOS App for App Store
    environment:
      flutter: stable
      xcode: 15.4
      vars:
        LC_TYPE: "en_US.UTF-8"

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Clean project
        script: |
          flutter clean

      - name: Build iOS release app
        script: |
          flutter build ipa --release --no-tree-shake-icons --codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_KEY
        issuer_id: $APP_STORE_ISSUER_ID
        key_id: $APP_STORE_KEY_ID
        submit_to_testflight: true
