workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: "com.matroodi.wholesale3"
        BUNDLE_NAME: "Matroodi Wholesale"
      groups:
        - ios_credentials
        - ios_signing

    credentials:
      ios:
        certificate: $CERTIFICATE_REFERENCE
        provisioning_profile: $PROFILE_REFERENCE

    scripts:
      - name: 🧹 Clean & Get Dependencies
        script: |
          flutter clean
          flutter pub get
          flutter precache --ios
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: 🏗️ Build iOS release .ipa
        script: |
          echo "🔐 Using certificate: $CERTIFICATE_REFERENCE"
          echo "📱 Using provisioning profile: $PROFILE_REFERENCE"
          flutter build ipa --release --no-tree-shake-icons --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
