workflows:
  ios-build:
    name: Build iOS App for App Store
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: 15.4
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.matroodi.wholesale3
      vars:
        LC_TYPE: "en_US.UTF-8"

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Update CocoaPods and Firebase dependencies
        script: |
          cd ios
          pod repo update
          pod update FirebaseSharedSwift FirebaseCore FirebaseCoreExtension
          cd ..

      - name: Clean project
        script: |
          flutter clean

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS release app
        script: |
          flutter build ipa --release --no-tree-shake-icons --codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_KEY
        issuer_id: $APP_STORE_ISSUER_ID
        key_id: $APP_STORE_KEY_ID
        submit_to_testflight: true
