name: new_app
description: "A new Flutter project."
publish_to: 'none'
version: 3.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  photo_view: ^0.14.0
  cached_network_image: ^3.2.1
  intl: ^0.18.0
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.2.5
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  convex_bottom_bar: ^3.0.0
  flutter_local_notifications: ^17.0.0
  dio: ^5.4.0
  path_provider: ^2.1.2
  #open_file: ^3.3.2
  permission_handler: ^11.3.0
  package_info_plus: ^4.2.0
  change_app_package_name: ^1.5.0
  rename: ^3.1.0
  firebase_core: 2.32.0
  firebase_auth: 4.19.5
  cloud_firestore: 4.17.5
  firebase_messaging: 14.9.2
  firebase_database: 10.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo.png
  android: true
  ios: true

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
