# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

use_frameworks!
use_modular_headers!

$FirebaseSDKVersion = '10.27.0'

target 'Runner' do
  flutter_application_path = '../'
  eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')))

  # Ensure Firebase libraries are pulled correctly
  pod 'Firebase/Core', $FirebaseSDKVersion
  pod 'Firebase/Firestore', $FirebaseSDKVersion
  pod 'Firebase/Auth', $FirebaseSDKVersion
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
